//Generated by DynTFTCodeGen.

{
    Copyright (C) 2026 VCC
    creation date: 15 Feb 2026
    initial release date: 15 Feb 2026

    author: VCC
    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:
    The above copyright notice and this permission notice shall be included
    in all copies or substantial portions of the Software.
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
    IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
    DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
    OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
}

unit DynTFTGUI;

{$IFNDEF IsMCU}
  {$DEFINE IsDesktop}
{$ENDIF} 

{$IFDEF IsDesktop}
interface
{$ENDIF}

uses
  DynTFTTypes, DynTFTConsts, DynTFTUtils, DynTFTBaseDrawing,
  DynTFTGUIObjects, DynTFTHandlers,

//<DynTFTComponents>
  DynTFTButton,
  //DynTFTArrowButton,
  //DynTFTPanel,
  //DynTFTCheckBox,
  //DynTFTScrollBar,
  //DynTFTItems,
  //DynTFTListBox,
  DynTFTLabel,
  //DynTFTRadioButton,
  //DynTFTRadioGroup,
  //DynTFTTabButton,
  //DynTFTPageControl,
  DynTFTEdit,
  DynTFTKeyButton,
  DynTFTVirtualKeyboard,
  //DynTFTComboBox,
  //DynTFTTrackBar,
  //DynTFTProgressBar,
  DynTFTMessageBox
  //DynTFTVirtualTable,
  //DynTFTVirtualKeyboardX2,
//<EndOfDynTFTComponents> - Do not remove or modify this line!

  
  {$IFDEF IsDesktop}
    , SysUtils
    {$IFDEF DynTFTFontSupport}, DynTFTFonts {$ENDIF}
  {$ENDIF}

  {$I DynTFTGUIAdditionalUnits.inc}
  ;


procedure DynTFT_GUI_Start;
procedure DrawGUI; //Made available for debugging or various performance improvements. Called by DynTFT_GUI_Start.


implementation


// Project name: GUI_VKPlugin.dyntftcg //Do not delete or modify this line!

procedure SetScreenActivity;
var
  i: Integer;
begin
  DynTFTAllComponentsContainer[0].Active := True;

  DynTFTAllComponentsContainer[0].ScreenColor := CL_DynTFTScreen_Background;

  for i := 1 to CDynTFTMaxComponentsContainer - 1 do
    DynTFTAllComponentsContainer[i].Active := False;

  DynTFT_Set_Pen(DynTFTAllComponentsContainer[0].ScreenColor, 1);
  DynTFT_Set_Brush(1, DynTFTAllComponentsContainer[0].ScreenColor, 0, 0, 0, 0);
  DynTFT_Rectangle(0, 0, TFT_DISP_WIDTH, TFT_DISP_HEIGHT);  //These constans are declared in TFT.pas. This unit is no longer present by default, in the uses section. Instead, it has to be manually added in DynTFTGUIAdditionalUnits.inc. 
end;

procedure RegisterAllComponentsEvents;
begin
  DynTFTRegisterButtonEvents;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTButton type: ' + IntToStr(DynTFTGetButtonComponentType));{$ENDIF}
  //DynTFTRegisterArrowButtonEvents;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTArrowButton type: ' + IntToStr(DynTFTGetArrowButtonComponentType));{$ENDIF}
  //DynTFTRegisterPanelEvents;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTPanel type: ' + IntToStr(DynTFTGetPanelComponentType));{$ENDIF}
  //DynTFTRegisterCheckBoxEvents;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTCheckBox type: ' + IntToStr(DynTFTGetCheckBoxComponentType));{$ENDIF}
  //DynTFTRegisterScrollBarEvents;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTScrollBar type: ' + IntToStr(DynTFTGetScrollBarComponentType));{$ENDIF}
  //DynTFTRegisterItemsEvents;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTItems type: ' + IntToStr(DynTFTGetItemsComponentType));{$ENDIF}
  //DynTFTRegisterListBoxEvents;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTListBox type: ' + IntToStr(DynTFTGetListBoxComponentType));{$ENDIF}
  DynTFTRegisterLabelEvents;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTLabel type: ' + IntToStr(DynTFTGetLabelComponentType));{$ENDIF}
  //DynTFTRegisterRadioButtonEvents;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTRadioButton type: ' + IntToStr(DynTFTGetRadioButtonComponentType));{$ENDIF}
  //DynTFTRegisterRadioGroupEvents;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTRadioGroup type: ' + IntToStr(DynTFTGetRadioGroupComponentType));{$ENDIF}
  //DynTFTRegisterTabButtonEvents;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTTabButton type: ' + IntToStr(DynTFTGetTabButtonComponentType));{$ENDIF}
  //DynTFTRegisterPageControlEvents;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTPageControl type: ' + IntToStr(DynTFTGetPageControlComponentType));{$ENDIF}
  DynTFTRegisterEditEvents;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTEdit type: ' + IntToStr(DynTFTGetEditComponentType));{$ENDIF}
  DynTFTRegisterKeyButtonEvents;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTKeyButton type: ' + IntToStr(DynTFTGetKeyButtonComponentType));{$ENDIF}
  DynTFTRegisterVirtualKeyboardEvents;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTVirtualKeyboard type: ' + IntToStr(DynTFTGetVirtualKeyboardComponentType));{$ENDIF}
  //DynTFTRegisterComboBoxEvents;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTComboBox type: ' + IntToStr(DynTFTGetComboBoxComponentType));{$ENDIF}
  //DynTFTRegisterTrackBarEvents;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTTrackBar type: ' + IntToStr(DynTFTGetTrackBarComponentType));{$ENDIF}
  //DynTFTRegisterProgressBarEvents;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTProgressBar type: ' + IntToStr(DynTFTGetProgressBarComponentType));{$ENDIF}
  DynTFTRegisterMessageBoxEvents;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTMessageBox type: ' + IntToStr(DynTFTGetMessageBoxComponentType));{$ENDIF}
  //DynTFTRegisterVirtualTableEvents;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTVirtualTable type: ' + IntToStr(DynTFTGetVirtualTableComponentType));{$ENDIF}
  //DynTFTRegisterVirtualKeyboardX2Events;        {$IFDEF IsDesktop}DynTFT_DebugConsole('DynTFTVirtualKeyboardX2 type: ' + IntToStr(DynTFTGetVirtualKeyboardX2ComponentType));{$ENDIF}
end;

procedure CreateGUI_Screen_0; //Tab
begin
  vkTest := DynTFTVirtualKeyboard_Create(0, 1, 55, 318, 184);
  {$IFDEF DynTFTFontSupport} 
    vkTest^.ActiveFont := {$IFDEF IsDesktop} PByte(@CAllFontSettings[-1]) {$ELSE}  {$ENDIF};
  {$ENDIF} 
  {$IFDEF IsDesktop}
    vkTest^.OnCharKey^ := VirtualKeyboard_OnCharKey;
  {$ELSE}
    vkTest^.OnCharKey := @VirtualKeyboard_OnCharKey;
  {$ENDIF}
  {$IFDEF IsDesktop}
    vkTest^.OnSpecialKey^ := VirtualKeyboard_OnSpecialKey;
  {$ELSE}
    vkTest^.OnSpecialKey := @VirtualKeyboard_OnSpecialKey;
  {$ENDIF}
  {$IFDEF DynTFTFontSupport}
    DynTFTSetVirtualKeyboardActiveFont(vkTest);
  {$ENDIF}

  edtValue := DynTFTEdit_Create(0, 1, 26, 318, 24);
end;

procedure DrawGUI;
begin
  CreateGUI_Screen_0;
  DynTFTRepaintScreenComponents(0, CREPAINTONSTARTUP, nil);
end;


{$IFDEF IsDesktop}
  {$IFDEF RTTIREG}
    procedure InitAllBinGUIObjectsToNil;
    var
      i: Integer;
    begin
      //No binary components
    end;
  {$ENDIF}
{$ENDIF}

  {$IFDEF RTTIREG}
    function CheckIntegerAndPointerSize: Boolean;  // returs True for success
    {$IFDEF IsMCU}
      type
        Pointer = ^Integer;
    {$ENDIF}
    begin
      if SizeOf(Integer) <> C_ProfileIntegerSize then
      begin
        DynTFTDisplayErrorMessage(CRTTIBADINTEGERSIZE, CL_BLUE);
        {$IFDEF IsDesktop} DynTFT_DebugConsole('.................................... ' + CRTTIBADINTEGERSIZE + ' ...  SizeOf(Integer) <> ' + IntToStr(C_ProfileIntegerSize) + '  See profile settings.'); {$ENDIF}
        Result := False;
        Exit;
      end;

      if SizeOf(Pointer) <> C_ProfilePointerSize then
      begin
        DynTFTDisplayErrorMessage(CRTTIBADIPOINTERSIZE, CL_BLUE);
        {$IFDEF IsDesktop} DynTFT_DebugConsole('.................................... ' + CRTTIBADIPOINTERSIZE + ' ...  SizeOf(Pointer) <> ' + IntToStr(C_ProfilePointerSize) + '  See profile settings.'); {$ENDIF}
        Result := False;
        Exit;
      end;

      Result := True;
    end;
  {$ENDIF}


procedure DynTFT_GUI_Start;
begin
  {$IFDEF IsDesktop}
    DynTFT_DebugConsole('Entering DynTFT_GUI_Start');

    {$IFDEF RTTIREG}
      InitAllBinGUIObjectsToNil;
    {$ENDIF}
  {$ENDIF}

  {$IFDEF RTTIREG}
    LinkHandlers;
  {$ENDIF}

  DynTFTInitInputDevStateFlags;

  DynTFTInitComponentTypeRegistration;
  DynTFTInitComponentContainers;    //must be called after InitComponentTypeRegistration
  RegisterAllComponentsEvents;

  SetScreenActivity;

  {$IFDEF RTTIREG}
    if not CheckIntegerAndPointerSize then
      Exit;
  {$ENDIF}

  DrawGUI;
end;

end.
