//Generated by DynTFTCodeGen.

{
    Copyright (C) 2026 VCC
    creation date: 15 Feb 2026
    initial release date: 15 Feb 2026

    author: VCC
    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:
    The above copyright notice and this permission notice shall be included
    in all copies or substantial portions of the Software.
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
    IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
    DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
    OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
}

unit DynTFTFonts;

//This unit should not be compiled for microcontroller.

interface

{$IFNDEF UserTFTCommands}  //this can be a project-level definition
  {$DEFINE mikroTFT}
{$ENDIF}


uses
  Graphics
  {$IFDEF mikroTFT} 
    , TFT
  {$ELSE}
    , {$INCLUDE UserDrawingUnits.inc}
  {$ENDIF}
  ;


const
  CAllFontSettings: array[-1..1] of TDynTFTFontSettings = (
    ( //TFT_fallbackFont  (Fallback font, used when the property mentions an undefined font.)
      FontName: 'Tahoma';
      IdentifierName: 'TFT_defaultFont';
      FontSize: 8;
      Bold: False;
      Italic: False;
      Underline: False;
      StrikeOut: True;
      Charset: 1;
      Pitch: TFontPitch(0)
    )
    ,
    ( //@Verdana29x32_ItalicUnderLine
      FontName: 'Verdana';
      IdentifierName: 'Verdana29x32_ItalicUnderLine';
      FontSize: 20;
      Bold: False;
      Italic: False;
      Underline: False;
      StrikeOut: False;
      Charset: 1;
      Pitch: TFontPitch(0)
    )
    ,
    ( //@Tahoma
      FontName: 'Tahoma';
      IdentifierName: 'Tahoma';
      FontSize: 8;
      Bold: False;
      Italic: False;
      Underline: False;
      StrikeOut: False;
      Charset: 0;
      Pitch: TFontPitch(0)
    )
  );

var
  Verdana29x32_ItalicUnderLine_Font: TDynTFTFontSettings;
  Tahoma_Font: TDynTFTFontSettings;

implementation


var
  i: Integer;

initialization
  Verdana29x32_ItalicUnderLine_Font := CAllFontSettings[0];
  Tahoma_Font := CAllFontSettings[1];
end.

